In [ ]:
#!pip install numpy

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [6]:
b = np.array([
  [1, 2, 3],
  [4, 5, 6]
])

print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
a.ndim

1

In [8]:
b.ndim

2

In [9]:
b.shape

(2, 3)

In [10]:
a.dtype

dtype('int64')

In [11]:
b.dtype

dtype('int64')

In [13]:
a.itemsize

8

In [14]:
a.size

3

In [15]:
b.size

6

In [19]:
foo = np.array([[1, 2, 3, 4, 5, 6, 7],
               [8, 9, 10, 11, 12, 13, 14]])

In [21]:
foo.shape

(2, 7)

In [22]:
foo.size

14

In [24]:
foo.ndim

2

In [27]:
print(foo[1,2] * 5)

50


In [32]:
a = np.random.rand(3,3).round(2)

In [34]:
np.full_like(a, 5, dtype='int32')

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]], dtype=int32)

In [41]:
np.random.randint(4, 7, size=(3, 3))
# random 3x3 matrix with elements between 4 and 6

array([[5, 4, 6],
       [6, 5, 5],
       [6, 4, 6]])

In [44]:
print(np.identity(5, dtype='int32'))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
a = np.ones((2,3))

b = np.full((3,2), 2)

print(a, b)

[[1. 1. 1.]
 [1. 1. 1.]] [[2 2]
 [2 2]
 [2 2]]


In [53]:
b = np.random.randint(0, 100, size = (3,2))
b

array([[37, 13],
       [53, 66],
       [ 8, 56]])

In [55]:
c = np.matmul(a,b)
c

array([[ 98., 135.],
       [ 98., 135.]])